language: python

python:
  - "3.7"

# command to install dependencies
install:
  - pip install -U -r henrique/requirements.txt

# command to run tests
script:
  - pytest

notifications:
  slack: 'foxytrixy:HZwjgEulu0umNtMJ1E9UhGPA#henrique'
