FROM python:3.7
MAINTAINER foxytrixy foxytrixy.bot@gmail.com

ARG ENV

# ENV PATH /usr/local/bin:$PATH
ENV LANG C.UTF-8
ENV FLASK_APP henrique.main.run
ENV FLASK_ENV development

RUN apt-get -y update
RUN apt-get -y dist-upgrade
RUN apt-get -y install build-essential libssl-dev libffi-dev nginx supervisor

COPY . /henrique
WORKDIR /henrique

RUN pip install --upgrade pip
RUN pip install -r henrique/requirements.txt
RUN pip install -r scripts/deploy/requirements.server.txt

RUN /henrique/scripts/deploy/uwsgi/run.bash

RUN /henrique/scripts/deploy/nginx/run.bash

RUN cp -f /henrique/scripts/deploy/nginx/henrique /etc/nginx/sites-available/
RUN rm -f /etc/nginx/sites-enabled/*
RUN ln -sf /etc/nginx/sites-available/henrique /etc/nginx/sites-enabled/

RUN cp -f /henrique/scripts/deploy/supervisor/super_uwsgi.conf /etc/supervisor/conf.d/

EXPOSE 80
EXPOSE 443

CMD nginx; supervisord -n
